### ISSUE TITLE
Plugin generates error: HTTP ERROR 500

### ISSUE THREAD

**Issue by awrog** [Himmlisch-Studios/grav-plugin-whistleblower#2]
This looks like a great plugin!
After installing it in a Grav v1.7.35, the site turns blank with error HTTP ERROR 500

Is the plugin compatible with the latest GRAV version?

**Comment by awrog** [comment]
Just tested in a fresh GRAV v1.7.35 install.
PHP Version 7.3.33, CURL enabled.
Unfortunately, after installing the plugin, the site goes blank, HTTP ERROR 500
console: Failed to load resource: the server responded with a status of 500 ()

**Comment by LuanHimmlisch** [comment]
Thanks, the plugin needs PHP 7.4 in order to work. I will update the composer.json

**Comment by LuanHimmlisch** [comment]
Done https://github.com/Himmlisch-Studios/grav-plugin-whistleblower/releases/tag/1.0.1
